### ISSUE TITLE
Install wget and alter crontab entries to restart master and tserver services

### ISSUE THREAD

**Issue by samkulkarni20** [yugabyte/utilities#18]
- The crontab entry at https://github.com/yugabyte/utilities/blob/master/scripts/create_universe.sh#L162 is unable to expand the $SSH_USER in echo command. This would prevent running the start_master.sh again as can be required in some cases like rebooting instance in terraform deployment.  
Similar with https://github.com/yugabyte/utilities/blob/master/scripts/create_universe.sh#L208 for start_tserver.sh script.

- The centOS-7 does not have wget preinstalled which is required to get the release tar of yugabyte-db. Thus, the installation fails on centOS-7.

**Comment by bhavin192** [comment]
Closing this as https://github.com/yugabyte/utilities/pull/15 is merged now.
